# Generated by Django 3.2.6 on 2021-10-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_per', '0002_organ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='midn',
            new_name='phon',
        ),
    ]
