# Generated by Django 3.2.6 on 2021-08-25 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='slug')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('time_crea', models.DateTimeField(auto_now_add=True)),
                ('time_upda', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Адреса',
                'verbose_name_plural': 'Адреса',
                'ordering': ['titl'],
            },
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='slug')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('time_crea', models.DateTimeField(auto_now_add=True)),
                ('time_upda', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Коды',
                'verbose_name_plural': 'Коды',
                'ordering': ['titl'],
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='slug')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('time_crea', models.DateTimeField(auto_now_add=True)),
                ('time_upda', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_crm.codes', verbose_name='Код заказа')),
            ],
            options={
                'verbose_name': 'Цвета',
                'verbose_name_plural': 'Цвета',
                'ordering': ['titl'],
            },
        ),
        migrations.CreateModel(
            name='Fasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='slug')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('time_crea', models.DateTimeField(auto_now_add=True)),
                ('time_upda', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_crm.codes', verbose_name='Код заказа')),
            ],
            options={
                'verbose_name': 'Крепеж',
                'verbose_name_plural': 'Крепеж',
                'ordering': ['titl'],
            },
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='slug')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('cont', models.TextField(blank=True, verbose_name='Содержание')),
                ('time_crea', models.DateTimeField(auto_now_add=True)),
                ('time_upda', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
                'ordering': ['titl'],
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surn', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('midn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('date_birt', models.DateField(blank=True, max_length=255, null=True, verbose_name='Дата рождения')),
                ('date_deat', models.DateField(blank=True, max_length=255, null=True, verbose_name='Дата смерти')),
                ('desc', models.TextField(blank=True, help_text='help_text', verbose_name='Рекомендации по обработке')),
                ('phot_natu', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('phot_reto', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото ретушированное')),
                ('is_p', models.BooleanField(default=True, verbose_name='Активен')),
                ('time_crea', models.DateTimeField(auto_now_add=True, verbose_name='Время соз')),
                ('time_upda', models.DateTimeField(auto_now=True, verbose_name='Время изм')),
                ('addr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_crm.address', verbose_name='Крепление')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_crm.codes', verbose_name='Код заказа')),
                ('colo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_crm.colors', verbose_name='Цвет рамки')),
                ('fast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_crm.fasts', verbose_name='Крепление')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-time_crea', 'surn'],
            },
        ),
    ]
