# Generated by Django 3.2.6 on 2021-09-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0002_items_date_fune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='is_p',
            new_name='agre',
        ),
    ]
