# Generated by Django 3.2.6 on 2021-09-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0004_auto_20210910_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='agre',
            new_name='is_p',
        ),
        migrations.RemoveField(
            model_name='items',
            name='fini',
        ),
    ]
