# Generated by Django 3.2.6 on 2021-09-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0005_auto_20210910_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='is_p',
            new_name='agre',
        ),
    ]
