# Generated by Django 3.2.6 on 2021-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0006_rename_is_p_items_agre'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='fini',
            field=models.BooleanField(default=True, verbose_name='Закончен'),
        ),
    ]
