# Generated by Django 3.2.6 on 2021-09-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0007_items_fini'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infos',
        ),
    ]
