# Generated by Django 3.2.6 on 2021-09-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0008_delete_infos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='slug')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('time_crea', models.DateTimeField(auto_now_add=True)),
                ('time_upda', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a_crm.codes', verbose_name='Код заказа')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиция',
                'ordering': ['titl'],
            },
        ),
    ]
