# Generated by Django 3.2.6 on 2021-09-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0009_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='posi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='a_crm.position', verbose_name='Положение'),
        ),
    ]
