# Generated by Django 3.2.6 on 2021-09-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0013_auto_20210926_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='coun',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
