# Generated by Django 3.2.6 on 2021-09-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0015_auto_20210929_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='phot_with',
            field=models.BooleanField(default=True, verbose_name='С фото?'),
        ),
    ]
