# Generated by Django 3.2.6 on 2021-09-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0020_auto_20210930_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='phot_with',
            field=models.BooleanField(verbose_name='С фото?'),
        ),
    ]
