# Generated by Django 3.2.6 on 2021-09-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0022_alter_items_phot_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='numb',
        ),
        migrations.AlterField(
            model_name='items',
            name='agre',
            field=models.BooleanField(default=False, verbose_name='Нужно ли прислать на согласование?'),
        ),
        migrations.AlterField(
            model_name='items',
            name='fini',
            field=models.BooleanField(default=False, verbose_name='Закончен'),
        ),
        migrations.AlterField(
            model_name='items',
            name='phot_with',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='С фото?'),
        ),
    ]
