# Generated by Django 3.2.6 on 2021-09-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0023_auto_20210930_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='coun',
            new_name='numb',
        ),
    ]
