# Generated by Django 3.2.6 on 2021-09-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0024_rename_coun_items_numb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='numb',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Количество'),
        ),
    ]
