# Generated by Django 3.2.6 on 2021-10-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0025_alter_items_numb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='agre',
            field=models.BooleanField(default=False, verbose_name='Согласовано'),
        ),
    ]
