# Generated by Django 3.2.6 on 2021-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crm', '0028_codes_phot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='date_birt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения умершего'),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_deat',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти умершего'),
        ),
        migrations.AlterField(
            model_name='items',
            name='date_fune',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи заказа'),
        ),
    ]
